# Imagen base
FROM node:20

# Crear directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install --production

# Copiar solo el código compilado
COPY dist ./dist

# Exponer puerto
EXPOSE 3000

# Comando para correr la app
CMD ["node", "dist/index.js"]
