export enum DBTables {
    ROLES = 'ROLES',
    USUARIOS = 'USUARIOS',
    EXPEDIENTE = 'EXPEDIENTE',
    INDICIO = 'INDICIO',
    REVISION_EXPEDIENTE = 'REVISION_EXPEDIENTE',
    LOG_ACCIONES = 'LOG_ACCIONES'
}
